import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const coolvetica = localFont({
  src: "../public/fonts/CoolveticaRg.otf",
  weight: "400",
  style: "normal",
  variable: "--font-coolvetica", // optional, lets you use Tailwind variable
});

export const metadata: Metadata = {
  title: "Angus Bodle Motorsport Photography",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${coolvetica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
